config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'teckels#index'
  resources :teckels do
    resources :reservations, only: [:new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/profile", to: "users#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :teckel

  STATUS = %w[Pending Accept Decline]

  validates :status, inclusion: { in: STATUS }
end

app/models/teckel.rb
class Teckel < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # ouvrir un ticket :
  # belongs_to :owner, class_name: "User", foreign_key: :user_id

  SPECIES = %w[Miniature Standard Kanichen]
  HAIR = %w[Short Long]
  SEX = %w[Female Male]

  validates :name, presence: true
  validates :species, presence: true, inclusion: { in: SPECIES }
  validates :hair, presence: true, inclusion: { in: HAIR }
  validates :age, presence: true, numericality: { only_integer: true }
  validates :sex, presence: true, inclusion: { in: SEX }
  validates :color, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  has_one_attached :photo
  validates :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_teckel_characteristic,
    against: [ :name, :species, :hair, :color, :age, :sex, :special_features, :description, :anecdote ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true
  validates :email, uniqueness: true

  has_many :teckels
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_params, only: [:edit, :update]

  def new
    @teckel = Teckel.find(params[:teckel_id])
    @reservation = Reservation.new
    authorize @reservation
  end

  def create
    @teckel = Teckel.find(params[:teckel_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    @reservation.teckel = @teckel
    authorize @reservation
    if @reservation.save
      flash[:notice] = 'your reservation is pending!'
      redirect_to profile_path
    else
      render :new
    end
  end
  def edit
    @user = current_user
    @teckel = Teckel.find(params[:teckel_id])
    authorize @reservation
  end

  def update
    @reservation.update(reservation_params)
    authorize @reservation
  end

  private

  def set_params
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:starting_date, :ending_date, :teckel_id, :user_id, :status)
  end
end

app/controllers/teckels_controller.rb
class TeckelsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :edit, :destroy, :update]
  before_action :set_params, only: [:show, :edit, :update, :destroy]


  def index
    if params[:query].present?
      @teckels = policy_scope(Teckel).search_by_teckel_characteristic(params[:query])
    else
      @teckels = policy_scope(Teckel).order(created_at: :desc)
    end
    @teckels = @teckels.geocoded
    @markers = @teckels.map do |teckel|
      {
        lat: teckel.latitude,
        lng: teckel.longitude,
        info_window: render_to_string(partial: "info_window", locals: { teckel: teckel }),
        image_url: helpers.asset_url("teckel-item.jpg")
      }
    end
  end

  def show
    @reservation = Reservation.new
    authorize @teckel
  end

  def new
    @teckel = current_user.teckels.new
    authorize @teckel
  end

  def create
    @teckel = current_user.teckels.new(teckel_params)

    authorize @teckel
    if @teckel.save
      redirect_to teckel_path(@teckel)
    else
      render :new
    end
  end

  def edit
    authorize @teckel
  end

  def update
    @teckel.update(teckel_params)
    authorize @teckel
    redirect_to profile_path
  end

  def destroy
    @teckel.destroy
    authorize @teckel
    redirect_to profile_path
  end

  private

  def set_params
    @teckel = Teckel.find(params[:id])
  end

  def teckel_params
    params.require(:teckel).permit(:name, :species, :hair, :color, :age, :sex, :address, :special_features, :description, :anecdote, :price, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
    authorize @user
    @reservation = Reservation.new
    @asked_reservations = @user.teckels.map(&:reservations).flatten
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teckeloc</title>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<link rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"> %>

app/views/reservations/_edit.html.erb
  <%= simple_form_for [user, reservation] do |f| %>
  <%= f.input :status, collection: Reservation::STATUS %>
  <%= f.button :submit %>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<header class="header">
  <div class="header__logo">
    <%= link_to root_path do %>
    <img class="teck" src="https://res.cloudinary.com/dfaupoje1/image/upload/v1653487862/teckel/teckel_ummbhi.jpg" alt="">
    <% end %>
  </div>

    <%= form_tag teckels_path, method: :get do %>
      <%= text_field_tag :query, params[:query], placeholder: "Find your dog ...", class: "header__search"%>
    <% end %>


  <div class="dropdown-center">
    <button class="btn btn-link text-decoration-none dropdown-toggle" type="button" id="dropdownCenterBtn" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://res.cloudinary.com/dfaupoje1/image/upload/v1653487869/teckel/teckel-item_p2odzz.jpg" class="avatar dropdown-toggle" alt="teckel">for more
    </button>
      <ul class="dropdown-menu">
        <% if user_signed_in? %>
        <%= link_to "Profile", profile_path, class: "dropdown-item" %>
        <%= link_to "Log-out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
        <%= link_to "Log-in", user_session_path, class: "dropdown-item" %>
        <%= link_to "Register",  new_user_registration_path, class: "dropdown-item" %>
        <% end %>
        <%= link_to "Add your teckel", new_teckel_path, class: "dropdown-item" %>

      </ul>
  </div>
</header>

app/views/teckels/_info_window.html.erb
<h4><%= link_to teckel.name, teckel_path(teckel) %></h4>
<p><%= cl_image_tag teckel.photo.key, height: 60, width: 60, crop: :fill %> </p>
<p><%= teckel.description %></p>
<p><%= teckel.price %>€</p>

app/views/teckels/edit.html.erb
<div class="form_background mb-5">
  <%= simple_form_for @teckel do |f| %>
  <div class="d-flex">
    <div class="form_part me-5 form_string description">
    <%= f.input :name, input_html: { class: "form_input"} %>
    <%= f.input :hair, collection: Teckel::HAIR, input_html: { class: "form_input" } %>
    <%= f.input :species, collection: Teckel::SPECIES, input_html: { class: "form_input" } %>
    <%= f.input :color, input_html: { class: "form_input" } %>
    <%= f.input :age, input_html: { class: "form_input" } %>
    <%= f.input :sex, collection: Teckel::SEX, input_html: { class: "form_input" }  %>
    <%= f.input :address, placeholder: '', input_html: { class: "d-none", data: { geocoder_target: "address" } }, wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  </div>
  <div class="form_part form_string description">
    <%= f.input :special_features, input_html: { class: "form_input" } %>
    <%= f.input :description, input_html: { class: "form_input" } %>
    <%= f.input :anecdote, input_html: { class: "form_input" } %>
    <%= f.input :price, input_html: { class: "form_input" } %>
    <%= f.input :photo, as: :file, input_html: { class: "form_input" } %>
      <div class="d-flex justify-content-between align-items-center mt-5">
        <%= f.button :submit, class: "btn btn-cutie btn-link" %>
        <%= link_to teckels_path do %>
          <button class="btn btn-cutie btn-link">Back</button>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/teckels/index.html.erb
<h1 class="profile_title">Welcome to teckeloc : the land of beautiful and strong angels</h1>
<hr>
<div style="width: 100%; height: 250px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<hr>
<div class="container-index">
  <% @teckels.each do |teckel| %>
    <div class="card_background">
      <%= link_to teckel_path(teckel) do %>
        <%= cl_image_tag teckel.photo.key, height: 300, width: 400, crop: :fill, class: "card_img underline" %>
        <div class="d-flex justify-content-between card_title pb-0 px-3 pt-2 mb-1">
          <p>Meet <%= teckel.name %></p>
          <p>5<i class="fa-solid fa-star"></i></p>
        </div>
        <div class="d-flex px-3 pb-2 mt-1">
          <p><%= teckel.description %></p>
        </div>
        <p class="card_descr px-3"></p>
        <div class="d-flex px-3 pb-2 mt-1">
          <p class="card_price"><%= teckel.price %>€</p>
        </div>
      <% end  %>
    </div>
  <% end %>
</div>

app/views/teckels/new.html.erb
<div class="form_background mb-5">
  <%= simple_form_for @teckel do |f| %>
  <div class="d-flex">
    <div class="form_part me-5 form_string description">
    <%= f.input :name, input_html: { class: "form_input"} %>
    <%= f.input :hair, collection: Teckel::HAIR, input_html: { class: "form_input" } %>
    <%= f.input :species, collection: Teckel::SPECIES, input_html: { class: "form_input" } %>
    <%= f.input :color, input_html: { class: "form_input" } %>
    <%= f.input :age, input_html: { class: "form_input" } %>
    <%= f.input :sex, collection: Teckel::SEX, input_html: { class: "form_input" }  %>
    <%= f.input :address, placeholder: '', input_html: { class: "d-none", data: { geocoder_target: "address" } }, wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  </div>
  <div class="form_part form_string description">
    <%= f.input :special_features, input_html: { class: "form_input" } %>
    <%= f.input :description, input_html: { class: "form_input" } %>
    <%= f.input :anecdote, input_html: { class: "form_input" } %>
    <%= f.input :price, input_html: { class: "form_input" } %>
    <%= f.input :photo, as: :file, input_html: { class: "form_input" } %>
      <div class="d-flex justify-content-between align-items-center mt-5">
        <%= f.button :submit, class: "btn btn-cutie btn-link" %>
        <%= link_to teckels_path do %>
          <button class="btn btn-cutie btn-link">Back</button>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/teckels/payment.html.erb
<div class="container-payment">
  <div class="container-payment-card">
    <div class="img-center">
      <img class="logo" src="https://res.cloudinary.com/dfaupoje1/image/upload/v1653487862/teckel/teckel_ummbhi.jpg" alt="">
    </div>
    <div class="section-payment">
      <p>
        Hi <%= @user.username %> we are now confirming your reservation !
        You will rent <%= @teckel.name %> <%= @teckel.user.username %>
        from the 1rst of June to the 23rd August 2022.
        Based on your rate of <%= @teckel.price %> euros per night,
        your potential payout should be  <%=  %> euros.
      </p>
    </div>
    <div class="section-payment">
      <div class="img-center">
        <h4><%= @teckel.name %></h4>
        <%= cl_image_tag @teckel.photo.key, height: 200, width: 300, crop: :fill, class:'card-payment-img' %>
      </div>
    </div>
    <div class="section-border section-border-empty">
      <p>Reservation recap</p>
    </div>
    <div class="section-payment section-border">
      <% @user.reservations.each do |reservation| %>
        <%= reservation.teckel.name %>
        <%= reservation.starting_date %>
        <%= reservation.ending_date %>
      <% end %>
    </div>
    <div class="section-payment">
      <p>
        Thank you <%= @user.username %> for booking our cutie <%= @teckel.name %>,
        we hope you will have a great experience !
        Best Regards from Teckeloc team.
      </p>
    </div>
  </div>
</div>

app/views/teckels/show.html.erb
<h1 class="profile_title"> Teckelou's profile</h1>
<hr>
<div class="container-show">
  <div class="container-card">
    <div class="card-show-img">
      <%= cl_image_tag @teckel.photo.key, height: 300, width: 400, crop: :fill %>
    </div>
    <div class="card-show">
      <h4 class="title_h4"> Meet our adorable <%= @teckel.name %></h4>
    </div>
    <hr>
    <div>
      <p>You can run with <%= @teckel.name %> with a max of 4:50/min</p>
      <p>You can feed him anything except chocolate</p>
      <p>Free canceling until 48h before</p>
    </div>
    <hr>
    <div>
      <p> <span class="title_p">Species:</span> <%= @teckel.species %></p>
      <p> <span class="title_p"> Hair:</span>  <%= @teckel.hair %></p>
      <p> <span class="title_p">Color:</span>  <%= @teckel.color %></p>
      <p> <span class="title_p">Sex:</span>  <%= @teckel.sex %></p>
      <p> <span class="title_p">Age:</span>  <%= @teckel.age %></p>
      <p> <span class="title_p">Description:</span>  <%= @teckel.description %></p>
      <p> <span class="title_p">Anecdote:</span>  <%= @teckel.anecdote %></p>
      <p> <span class="title_p">Special features:</span>  <%= @teckel.special_features %></p>

    </div>
    <hr>
    <div>
      <p>How that service works ? Teckeloc is a simple simple services where you can rent a Teckel from his owner. The owner rent his dog for a stated duration. This does not mean this is your dog but that you can take out or pet him as he pleased. The dog is human being and can’t be forced to do anything, Assuming you already knew that no refund are possible because the dog didn’t act as you expected.</p>
    </div>
    <hr>
    <div class="apart">
      <% if user_signed_in? %>
        <% if policy(@teckel).edit? %>
          <%= link_to "Update", edit_teckel_path(@teckel), class:'btn btn-cutie btn-link' %>
        <% end %>
        <% if policy(@teckel).destroy? %>
          <%= link_to "Delete", teckel_path(@teckel), method: :delete,  data: { confirm: "Are you sure?" }, class:'btn btn-cancel btn-decline-link' %>
        <% end %>
      <% end %>

      <%= link_to "Back to Home page", teckels_path, class:'btn btn-cutie btn-link' %>
  </div>

  </div>
<% if @teckel.user != current_user %>
  <div class="container-recap">
    <div class="card-show-img">
      <%= cl_image_tag @teckel.photo.key, height: 150, width: 200, crop: :fill %>
    </div>
     <div>

      <h4>Calendar</h4>
       <%= simple_form_for [@teckel, @reservation] do |f| %>
        <%= f.input :starting_date %>
        <%= f.input :ending_date %>
      <div>
        <p>
          Price detail :  <%= @teckel.price %>€/night
        </p>
      </div>
      <div class="card-show-recap">
       <p><%= f.button :submit, "Book my cutie", class:'btn btn-cutie btn-link' %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/users/profile.html.erb
<h1 class="profile_title">Profile</h1>

<hr>

<h3 class="title_h3">my lovely teckels</h3>
<div class="container-index">
  <% @user.teckels.each do |teckel|%>
    <div class="card_background">
        <%= link_to teckel_path(teckel) do %>
        <%= cl_image_tag teckel.photo.key, height: 300, width: 400, crop: :fill, class: "card_img" %>
        <div class="d-flex justify-content-between card_title pb-0 px-3 pt-2 mb-1">
          <p>Meet <%= teckel.name %></p>
          <p>5<i class="fa-solid fa-star"></i></p>
        </div>
        <p class="card_descr px-3"></p>
        <p class="p-padding-payment"><%= teckel.description %></p>
        <div class="d-flex px-3 pb-2 mt-1">
          <p class="card_price"><%= teckel.price %>€</p>
        </div>
      <% end  %>
    </div>
  <% end %>
</div>

  <div class="reservation_link">
    <%= link_to "Add a pet",  new_teckel_path, class:"btn btn-cutie btn-link" %>
  </div>

  <hr>

  <h3 class="title_h3">They want my teckel </h3>
  <div class="container-payment">
   <% @asked_reservations.each do |reservation| %>
    <div class="card_background">
      <%= link_to  teckel_path(reservation.teckel) do%>
        <%= cl_image_tag reservation.teckel.photo.key, height: 300, width: 400, crop: :fill, class: "card_img" %>
        <p class="teckel_name description"><%= reservation.teckel.name %></p>
        <p class="description"> <%= reservation.teckel.description %></p>
        <p class="p-padding">Dates : <%= reservation.starting_date %> to <%= reservation.ending_date %></p>
        <p class="p-padding">Renter : <%= reservation.user.username %></p>
        <div class='p-padding'>
          <%= simple_form_for [reservation.teckel, reservation] do |f| %>
            <%= f.input :status, collection: Reservation::STATUS %>
            <%= f.button :submit, class:'btn btn-cutie btn-link'%>
          <% end %>
        </div>
      <% end %>
      <div class="d-flex justify-content-between card_title pb-0 px-3 pt-2 mb-1">
        <p> <%= reservation.teckel.age %> years old</p>
        <p>5<i class="fa-solid fa-star"></i></p>
      </div>
      <p class="card_descr px-3"></p>
      <div class="d-flex px-3 pb-2 mt-1">
        <p class="card_price"><%= reservation.teckel.price %>€ per night</p>
      </div>
    </div>
  <% end %>
    </div>
</div>
<hr>
<div>
 <h3 class="title_h3">My reservations as renter</h3>
  <div class="container-payment">
    <% @user.reservations.each do |reservation| %>
      <div class="container-payment-card">
        <div class="img-center">
          <img class="logo" src="https://res.cloudinary.com/dfaupoje1/image/upload/v1653487862/teckel/teckel_ummbhi.jpg" alt="">
        </div>
        <% if reservation.status == "Accept" %>
         <div class="section-payment">
          <p>
            Hi <%= @user.username %> we just confirmed your reservation !
            You will rent <%= reservation.teckel.name %> from <%= @user.username %>
            from <%= reservation.starting_date %> to the <%= reservation.ending_date %>.
            Based on the rate of <%= reservation.teckel.price%>€ per night.
          </p>
        </div>
        <div class="section-payment">
          <div class="img-center">
            <h3 class="title_h3"><%= link_to reservation.teckel.name, teckel_path(reservation.teckel) %></h3>
            <%= cl_image_tag reservation.teckel.photo.key, class:'card-payment-img' %>
          </div>
        </div>
        <div class="section-border section-border-empty">
          <p>Reservation recap</p>
        </div>
          <div class="section-payment section-border-bottom">
            <p>Renting from <%= reservation.starting_date %> to <%= reservation.ending_date %></p>
            <% t = reservation.ending_date - reservation.starting_date %>
            <p>
              Thank you <%= @user.username %> for booking our cutie <%= @user.teckels.name %>,
              we hope you will have a great experience !
            </p>
            <p>
              Best Regards from Teckeloc team.
              <hr>
              Status : <%= reservation.status %>
            </p>
          </div>
        <% elsif reservation.status == "Decline" %>
         <div class="section-payment">
          <p>
            Hi <%= @user.username %> we are sorry but your reservation has been declined
            for the rental of <%= reservation.teckel.name %> from <%= @user.username %>.
          </p>
        </div>
        <div class="section-payment">
          <div class="img-center">
            <h3 class="title_h3"><%= link_to reservation.teckel.name, teckel_path(reservation.teckel) %></h3>
            <%= cl_image_tag reservation.teckel.photo.key, class:'card-payment-img' %>
          </div>
        </div>
        <div class="section-border section-border-empty">
          <p>Reservation recap</p>
        </div>
          <div class="section-payment section-border-bottom">
            <p>Renting from <%= reservation.starting_date %> to <%= reservation.ending_date %></p>
            <% t = reservation.ending_date - reservation.starting_date %>
            <p>
              Hi We are sorry <%= @user.username %> but your reservation for <%= @user.teckels.name %> has been declined !
            </p>
            <p>
              Best Regards from Teckeloc team.
              <hr>
              Status : <%= reservation.status %>
            </p>
          </div>
        <% else %>
         <div class="section-payment">
          <p>
            Hi <%= @user.username %> we are now waiting to confirm your reservation !
            You want to rent <%= reservation.teckel.name %> from <%= @user.username %>
            from from <%= reservation.starting_date %> to the <%= reservation.ending_date %>.
            Based on the rate of <%= reservation.teckel.price%>€ per night.
          </p>
        </div>
        <div class="section-payment">
          <div class="img-center">
            <h3 class="title_h3"><%= link_to reservation.teckel.name, teckel_path(reservation.teckel) %></h3>
            <%= cl_image_tag reservation.teckel.photo.key, class:'card-payment-img' %>
          </div>
        </div>
        <div class="section-border section-border-empty">
          <p>Reservation recap</p>
        </div>
        <div class="section-payment section-border-bottom">
            <p>Renting from <%= reservation.starting_date %> to <%= reservation.ending_date %></p>
            <% t = reservation.ending_date - reservation.starting_date %>
            <p>
              Hi <%= @user.username %>  your reservation for <%= @user.teckels.name %> is pending...!
            </p>
            <p>
              Best Regards from Teckeloc team.
              <hr>
              Status : <%= reservation.status %>
            </p>
        </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>